### ISSUE TITLE
feat: 📦 Screen: Account 

### ISSUE THREAD

**Issue by Chocolatamargo2607** [Chocolatamargo2607/UD.PPC.MyPlantSitter#1]
# Requierements
## Mockup
🔗 [Link](https://excalidraw.com/#room=20312337fc2180a0a6c3,9LA3NsRTg0xzP2Inpw6lww)
## Task
- [x] Style: ✨ Create banner imagen -> [Imagen](https://github.com/Chocolatamargo2607/UD.PPC.MyPlantSitter/blob/main/app/src/main/res/drawable/logo.png)
- [x] Style: ✨ Create sections of 'user information'
  - Name
  - Email
- [x] Style: ✨ Create button 'modify information'
- [x] Style: ✨ Create button 'delete account'
- [x] Style: ✨ Create button 'log-out'

**Comment by SP3KTRO** [comment]
Done
