### ISSUE TITLE
feat: 📦 Modal 'my plant' 

### ISSUE THREAD

**Issue by Chocolatamargo2607** [Chocolatamargo2607/UD.PPC.MyPlantSitter#3]
# Requierements
>[!NOTE]
> The modal should be displayed when clicking on a plant in the "My plants" list 
## Mockup
🔗 [Link](https://excalidraw.com/#room=20312337fc2180a0a6c3,9LA3NsRTg0xzP2Inpw6lww)
## Task
- [x] Style: ✨ Create title plant (plant name)
- [x] Style: ✨ Create plant description (plant information)
- [x] Style: ✨ Create button 'remove plant'
- [x] Style: ✨ Create button 'modify plant'

**Comment by SP3KTRO** [comment]
ready
