### ISSUE TITLE
feat: 📦 Screen: Register my plants

### ISSUE THREAD

**Issue by Chocolatamargo2607** [Chocolatamargo2607/UD.PPC.MyPlantSitter#4]
# Requierements
## Mockup
🔗 [Link](https://excalidraw.com/#room=20312337fc2180a0a6c3,9LA3NsRTg0xzP2Inpw6lww)
## Task
- [x] Style: ✨ Create input: Plant name
- [x] Style: ✨ Create combo box 'category of plant' 
- [x] Style: ✨ Create button 'Resgister plant'
