### ISSUE TITLE
feat: 📦 Screen: Main

### ISSUE THREAD

**Issue by Chocolatamargo2607** [Chocolatamargo2607/UD.PPC.MyPlantSitter#5]
# Requierements
## Mockup
🔗 [Link](https://excalidraw.com/#room=20312337fc2180a0a6c3,9LA3NsRTg0xzP2Inpw6lww)
## Task
- [x] Style: ✨ Create nav bar
- [x] Style: ✨ Add banner image (Find banner in screen account)
- [x] Style: ✨ Create list: It will do task
- [x] Style: ✨ Create button 'Register assignment'
