### ISSUE TITLE
feat: 📦 Screen: Register assigment

### ISSUE THREAD

**Issue by Chocolatamargo2607** [Chocolatamargo2607/UD.PPC.MyPlantSitter#6]
# Requierements
## Mockup
🔗 [Link](https://excalidraw.com/#room=20312337fc2180a0a6c3,9LA3NsRTg0xzP2Inpw6lww)
## Task
- [x] Style: ✨ Create combo box 'Plant to assign'
- [x] Style: ✨ Create input 'Description assigment'
- [x] Style: ✨ Create input 'Date of assigment'
- [x] Stule: ✨ Create button 'Register assigment'
