### ISSUE TITLE
feat: 📦  Modal 'assignment'

### ISSUE THREAD

**Issue by Chocolatamargo2607** [Chocolatamargo2607/UD.PPC.MyPlantSitter#7]
# Requierements
>[!NOTE]
> The modal should be displayed when clicking on a assignment in the "Main (screen)" list 
## Mockup
🔗 [Link](https://excalidraw.com/#room=20312337fc2180a0a6c3,9LA3NsRTg0xzP2Inpw6lww)
## Task
- [x] Style: ✨ Create title assignment (assignment name)
- [x] Style: ✨ Create plant description (assignment  information)
- [x] Style: ✨ Create button 'remove assignment '
- [x] Style: ✨ Create button 'modify assignment '
