### ISSUE TITLE
feat: 📦 Modal 'plant'

### ISSUE THREAD

**Issue by Chocolatamargo2607** [Chocolatamargo2607/UD.PPC.MyPlantSitter#8]
# Requierements
>[!NOTE]
> The modal should be displayed when clicking on a plant in the "Plants" list 
## Mockupdisplayed 
🔗 [Link](https://excalidraw.com/#room=20312337fc2180a0a6c3,9LA3NsRTg0xzP2Inpw6lww)
## Task
- [x] Style: ✨ Create title plant (plant name)
- [x] Style: ✨ Create container image plant
- [x] Style: ✨ Create plant description (plant information)
